baseURL = "https://devner.se/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "devner"
  subtitle    = "self proclaimed tech and code enthusiast"
  copyright   = "© 2019"

  cover       = "images/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  instagramName = "marcus_alexander_"
  fbName = "vaariou"
  githubName = "agerro"
  linkedinName = "marcus-karlsson-a6aa69b3"
  mediumName = ""

  logo = "images/logo.png"
  orgName = "devner"
  orgWebsite = "https://devner.se"
  orgDescription = "devops"

  showSupport = true

  author = "MK"
  authorAvatar = "img/test.jpeg"
  authorLocation = "Sweden, SV"
  authorWebsite = "https://devner.se"
  authorDescription = "self proclaimed tech and code enthusiast"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 100

[[menu.main.aws]]
  name = "#aws"
  url = "/projects/aws"
  weight = 98

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 98

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 95


